# Generated by Django 4.2.6 on 2023-12-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat", name="like", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat", name="unlike", field=models.BooleanField(default=False),
        ),
    ]
